Add 2020 schedule
paug/android-makers-2020 pull request #13
Opened 2020-04-07 09:51 UTC by Oleur

2020-04-07 10:01 UTC, benju69 commented
I will deploy this and test it :) also we need to re add schedule tab

2020-04-07 10:15 UTC, CmoaToto requested changes
Top ! I leaved few comments but globally 👏

2020-04-07 10:15 UTC, CmoaToto commented on data/database/schedule.json
> +            "items": []
I think this item is uneeded. Remove it so the break fill the 3 first tracks

2020-04-07 10:15 UTC, CmoaToto commented on data/database/schedule.json
>          "title": "Moebius",
You must change the tracks names

2020-04-07 10:15 UTC, CmoaToto commented on data/database/schedule.json
> +            "items": []
same, remove this item so the break fills the 3 first tracks

2020-04-07 10:15 UTC, CmoaToto commented on data/database/schedule.json
>          "title": "Moebius",
same, change tracks names

2020-04-07 10:17 UTC, Oleur commented on data/database/schedule.json
>          "title": "Moebius",
Any ideas on the names?

2020-04-08 12:03 UTC, martinbonnin approved these changes
Nice 🎉

2020-04-08 12:15 UTC, benju69 requested changes
- [x] Déplacer  :📼🇺🇸*/🇫🇷Riding the state flow le même jour à 10h

- [x] ajouter un welcome message cross track de 10h à 10h15
- [x] link la keynote et l'étendre sur toutes les tracks
- [x] retirer : Get started with Jetpack Compose
- [x] remplacer Welcome onBoard! à 12h30 par 🇫🇷Utilisez les DSL Kotlin pour vos scripts Gradle - 20min - anytime
- [x] à déplacer dans la track 2 FR : Intégrer plusieurs librairies Kotlin Native dans vos apps Android/iOS mardi à 13:30

2020-04-08 14:43 UTC, Oleur commented
> Déplacer :
> vhsus*/frRiding the state flow le même jour à 10h
> 
> ajouter un welcome message cross track de 10h à 10h15
> link la keynote et l'étendre sur toutes les tracks
> retirer : Get started with Jetpack Compose
> remplacer Welcome onBoard! à 12h30 par frUtilisez les DSL Kotlin pour vos scripts Gradle - 20min - anytime
> à déplacer dans la track 2 FR : Intégrer plusieurs librairies Kotlin Native dans vos apps Android/iOS mardi à 13:30

On it!

2020-04-10 08:48 UTC, benju69 approved these changes

2020-04-10 08:48 UTC, merged